version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - ../.env.${NODE_ENV}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: novabook-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=novabook
    ports:
      - "5432:5432"
    volumes:
      - novabook-db-data:/var/lib/postgresql/data

volumes:
  novabook-db-data:
